### PR TITLE
M05 views - Companies

### PR DESCRIPTION
**Pull request by dcarolinahdev**
CiaForm page component
---

-   it renders a form to create a new Company in path /cia-form

Phone view (minga size):

image

Laptop view (minga size):

image

### CODE REVIEW

**Review by santivanegas16 — COMMENTED** [review]
Review the agreed input sizes

**Comment by dcarolinahdev** [comment]
> Review the agreed input sizes

Thanks! I forgot it, It was changed

**Review by JALZ2003 — APPROVED** [review]
Lo veo todo en orden, perfecto, Solucione un pequeño conflicto en cuanto a el router, nada que generase mucho conflicto, eso sucedió por que primero se realizo el pull requested de Santi, todo perfecto.

**Review by santivanegas16 — APPROVED** [review]
it's ok, we should check the images that each one uploaded.

**Pull request merged**
